package com.affaince.benefit.scheme;

public enum ArithmeticOperator {
    ADDITION,
    LOOPADDITION,
    SUBTRACTION,
    MULTIPLICATION,
    DIVISION,
    MODULUS,
    GREATERTHAN,
    LOOPGREATERTHAN,
    GREATERTHANEQUALTO,
    LOOPGREATERTHANEQUALTO,
    LESSTHAN,
    LOOPLESSTHAN,
    LESSTHANEQUALTO,
    LOOPLESSTHANEQUALTO,
    EQUALTO,
    LOOPEQUALTO,
    NOTEQUALTO,
    LOOPNOTEQUALTO,
    TERNARY,
    ASSIGN,
    OR,
    AND,
    STRCONCAT,
    STRUPPERCASE,
    STRLOWERCASE
}
